### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by xielaobanyy** [HustAlexander/MCWSS#1]
Hello, I would like to ask why this error is reported after running train.py：
       **f = h5py.File(self.datas[index],'r')
IndexError: list index out of range**

**Comment by HustAlexander** [comment]
Thank you for finding this error. It casued by a mismatch between the group.py and dataset.py, resulting on the length of the triaining data and the length of the label_cross.txt being different. We have updated the group.py.

**Comment by HustAlexander** [comment]
> Hello, I would like to ask why this error is reported after running train.py： **f = h5py.File(self.datas[index],'r') IndexError: list index out of range**

Thank you for finding this error. It casued by a mismatch between the group.py and dataset.py, resulting on the length of the triaining data and the length of the label_cross.txt being different. We have updated the group.py

**Comment by xielaobanyy** [comment]
Thank you very much for your reply! The problem has been solved, Then I encountered the following problem when running the test.py file: 
**_img.set_data_dtype(dtype=np.ushort)
TypeError: set_data_dtype() got an unexpected keyword argument 'dtype',_** 
I replaced the data type in brackets with ''np.ushort'', and the program runs normally.

**Comment by HustAlexander** [comment]
> Thank you very much for your reply! The problem has been solved, Then I encountered the following problem when running the test.py file: **_img.set_data_dtype(dtype=np.ushort) TypeError: set_data_dtype() got an unexpected keyword argument 'dtype',_** I replaced the data type in brackets with ''np.ushort'', and the program runs normally.

Yes, I met this problem somtimes, maybe it is caused by different python version.
